export const colors = {
  background: "#F5F6FA",
  canvas: "#F5F6FA",
  surface: "#FFFFFF",
  surfaceMuted: "#FBFCFE",
  surfaceSubtle: "#F1F4F9",
  surfaceBrand: "#FFF8E7",
  surfaceInfo: "#EEF4FF",
  surfaceSuccess: "#ECFBF0",
  surfaceWarning: "#FFF7E3",
  surfacePurple: "#F5ECFF",
  surfaceDanger: "#FFF1F2",
  border: "#E2E7F0",
  borderSoft: "#EDF1F6",
  borderStrong: "#D4DCE7",
  textPrimary: "#273043",
  textSecondary: "#6B7486",
  textMuted: "#98A1B2",
  textOnPrimary: "#FFFFFF",
  textInverse: "#FFFFFF",
  primary: "#D6A937",
  primaryStrong: "#BE9224",
  primaryMuted: "#F5E2A6",
  primaryContrast: "#8C6710",
  info: "#4B7BFF",
  infoStrong: "#2F62E8",
  infoMuted: "#DCE8FF",
  infoContrast: "#3159BC",
  success: "#49C964",
  successStrong: "#32954A",
  successMuted: "#D9F6E0",
  successContrast: "#2E8744",
  warning: "#F1B133",
  warningStrong: "#B77808",
  warningMuted: "#FFF0C9",
  warningContrast: "#A56A00",
  purple: "#9B57F6",
  purpleStrong: "#8043DB",
  purpleMuted: "#EEDFFF",
  purpleContrast: "#6B2FC4",
  danger: "#FF666D",
  dangerStrong: "#E24952",
  dangerMuted: "#FFE2E5",
  dangerContrast: "#C73D44",
  overlay: "rgba(21, 28, 40, 0.44)",
  shadow: "#121A2A",
  white: "#FFFFFF",
  black: "#000000",
} as const;

export const tonePalette = {
  brand: {
    background: colors.surfaceBrand,
    border: colors.primaryMuted,
    iconBackground: colors.primaryMuted,
    iconForeground: colors.primary,
    text: colors.primaryContrast,
  },
  danger: {
    background: colors.surfaceDanger,
    border: colors.dangerMuted,
    iconBackground: colors.dangerMuted,
    iconForeground: colors.danger,
    text: colors.dangerContrast,
  },
  info: {
    background: colors.surfaceInfo,
    border: colors.infoMuted,
    iconBackground: colors.infoMuted,
    iconForeground: colors.info,
    text: colors.infoContrast,
  },
  neutral: {
    background: colors.surface,
    border: colors.border,
    iconBackground: colors.surfaceSubtle,
    iconForeground: colors.textSecondary,
    text: colors.textPrimary,
  },
  purple: {
    background: colors.surfacePurple,
    border: colors.purpleMuted,
    iconBackground: colors.purpleMuted,
    iconForeground: colors.purple,
    text: colors.purpleContrast,
  },
  success: {
    background: colors.surfaceSuccess,
    border: colors.successMuted,
    iconBackground: colors.successMuted,
    iconForeground: colors.success,
    text: colors.successContrast,
  },
  warning: {
    background: colors.surfaceWarning,
    border: colors.warningMuted,
    iconBackground: colors.warningMuted,
    iconForeground: colors.warning,
    text: colors.warningContrast,
  },
} as const;

export const statusPalette = {
  connecting: {
    background: colors.surfaceWarning,
    border: colors.warningMuted,
    dot: colors.warning,
    text: colors.warningContrast,
  },
  disabled: {
    background: colors.surfaceSubtle,
    border: colors.borderStrong,
    dot: colors.textMuted,
    text: colors.textSecondary,
  },
  empty: {
    background: colors.surface,
    border: colors.borderStrong,
    dot: "#A7AFBC",
    text: colors.textSecondary,
  },
  error: {
    background: colors.surfaceDanger,
    border: colors.dangerMuted,
    dot: colors.danger,
    text: colors.dangerContrast,
  },
  idle: {
    background: colors.surfaceInfo,
    border: colors.infoMuted,
    dot: colors.info,
    text: colors.infoContrast,
  },
  occupied: {
    background: colors.surfaceInfo,
    border: colors.infoMuted,
    dot: colors.info,
    text: colors.infoContrast,
  },
  open: {
    background: colors.surfaceInfo,
    border: colors.infoMuted,
    dot: colors.info,
    text: colors.infoContrast,
  },
  paid: {
    background: colors.surfaceSuccess,
    border: colors.successMuted,
    dot: colors.success,
    text: colors.successContrast,
  },
  paymentPending: {
    background: colors.surfaceWarning,
    border: colors.warningMuted,
    dot: colors.warning,
    text: colors.warningContrast,
  },
  ready: {
    background: colors.surfaceSuccess,
    border: colors.successMuted,
    dot: colors.success,
    text: colors.successContrast,
  },
} as const;

export type ToneName = keyof typeof tonePalette;
export type StatusName = keyof typeof statusPalette;
