import {
  MenuCategory,
  MenuProduct,
  OrderDetail,
  TableSummary,
} from "../types/domain";

function buildTodayTime(hours: number, minutes: number) {
  const date = new Date();
  date.setHours(hours, minutes, 0, 0);

  return date.toISOString();
}

export const MOCK_TABLES: TableSummary[] = [
  {
    activeOrderId: "order-1",
    areaLabel: "Salon",
    assignedWaiterName: "Ahmet Yılmaz",
    guestCount: 4,
    id: "table-1",
    label: "Table 1",
    seats: 4,
    status: "occupied",
    totalAmount: 850.5,
    updatedAt: buildTodayTime(14, 30),
  },
  {
    areaLabel: "Salon",
    guestCount: 0,
    id: "table-2",
    label: "Table 2",
    seats: 4,
    status: "empty",
    totalAmount: 0,
    updatedAt: buildTodayTime(14, 42),
  },
  {
    activeOrderId: "order-3",
    areaLabel: "Salon",
    assignedWaiterName: "Ahmet Yılmaz",
    guestCount: 2,
    id: "table-3",
    label: "Table 3",
    seats: 4,
    status: "paymentPending",
    totalAmount: 425,
    updatedAt: buildTodayTime(15, 15),
  },
  {
    activeOrderId: "order-4",
    areaLabel: "Salon",
    assignedWaiterName: "Ahmet Yılmaz",
    guestCount: 6,
    id: "table-4",
    label: "Table 4",
    seats: 6,
    status: "occupied",
    totalAmount: 1240.75,
    updatedAt: buildTodayTime(13, 45),
  },
  {
    areaLabel: "Salon",
    guestCount: 0,
    id: "table-5",
    label: "Table 5",
    seats: 4,
    status: "empty",
    totalAmount: 0,
    updatedAt: buildTodayTime(14, 5),
  },
  {
    activeOrderId: "order-6",
    areaLabel: "Salon",
    assignedWaiterName: "Ahmet Yılmaz",
    guestCount: 3,
    id: "table-6",
    label: "Table 6",
    seats: 4,
    status: "occupied",
    totalAmount: 620.25,
    updatedAt: buildTodayTime(15, 0),
  },
];

export const MOCK_ORDERS: Record<string, OrderDetail> = {
  "table-1": {
    id: "order-1",
    items: [
      {
        id: "item-1",
        name: "Izgara Köfte",
        productId: "product-kofte",
        quantity: 2,
        unitPrice: 145,
      },
      {
        id: "item-2",
        name: "Karışık Salata",
        productId: "product-salad",
        quantity: 1,
        unitPrice: 65,
      },
      {
        id: "item-3",
        name: "Mercimek Çorbası",
        productId: "product-soup",
        quantity: 2,
        unitPrice: 45,
      },
      {
        id: "item-4",
        name: "Kaşarlı Pide",
        productId: "product-pide",
        quantity: 2,
        unitPrice: 202.75,
      },
    ],
    status: "open",
    subtotal: 850.5,
    tableId: "table-1",
    tax: 0,
    total: 850.5,
    updatedAt: buildTodayTime(14, 30),
  },
  "table-3": {
    id: "order-3",
    items: [
      {
        id: "item-5",
        name: "Izgara Tavuk",
        productId: "product-grilled-chicken",
        quantity: 1,
        unitPrice: 245,
      },
      {
        id: "item-6",
        name: "Salata",
        productId: "product-salad",
        quantity: 1,
        unitPrice: 80,
      },
      {
        id: "item-7",
        name: "Limonata",
        productId: "product-lemonade",
        quantity: 2,
        unitPrice: 50,
      },
    ],
    status: "paymentPending",
    subtotal: 425,
    tableId: "table-3",
    tax: 0,
    total: 425,
    updatedAt: buildTodayTime(15, 15),
  },
  "table-4": {
    id: "order-4",
    items: [
      {
        id: "item-8",
        name: "Karışık Izgara",
        productId: "product-mixed-grill",
        quantity: 3,
        unitPrice: 310.25,
      },
      {
        id: "item-9",
        name: "Meze Tabağı",
        productId: "product-meze",
        quantity: 1,
        unitPrice: 310,
      },
    ],
    status: "open",
    subtotal: 1240.75,
    tableId: "table-4",
    tax: 0,
    total: 1240.75,
    updatedAt: buildTodayTime(13, 45),
  },
  "table-6": {
    id: "order-6",
    items: [
      {
        id: "item-10",
        name: "Mantı",
        productId: "product-manti",
        quantity: 2,
        unitPrice: 180.125,
      },
      {
        id: "item-11",
        name: "Ayran",
        productId: "product-ayran",
        quantity: 2,
        unitPrice: 30,
      },
      {
        id: "item-12",
        name: "Çay",
        productId: "product-tea",
        quantity: 4,
        unitPrice: 50,
      },
    ],
    status: "open",
    subtotal: 620.25,
    tableId: "table-6",
    tax: 0,
    total: 620.25,
    updatedAt: buildTodayTime(15, 0),
  },
};

export const MOCK_MENU_CATEGORIES: MenuCategory[] = [
  {
    id: "grill",
    label: "Grill",
    sortOrder: 1,
  },
  {
    id: "drinks",
    label: "Drinks",
    sortOrder: 2,
  },
  {
    id: "dessert",
    label: "Dessert",
    sortOrder: 3,
  },
];

export const MOCK_MENU_PRODUCTS: MenuProduct[] = [
  {
    categoryId: "grill",
    id: "product-adana",
    isAvailable: true,
    name: "Adana Kebap",
    price: 260,
  },
  {
    categoryId: "grill",
    id: "product-kofte",
    isAvailable: true,
    name: "Izgara Köfte",
    price: 145,
  },
  {
    categoryId: "grill",
    id: "product-sea-bass",
    isAvailable: true,
    name: "Sea Bass",
    price: 540,
  },
  {
    categoryId: "grill",
    id: "product-burger",
    isAvailable: true,
    name: "Burger",
    price: 310,
  },
  {
    categoryId: "grill",
    id: "product-grilled-chicken",
    isAvailable: true,
    name: "Izgara Tavuk",
    price: 245,
  },
  {
    categoryId: "grill",
    id: "product-mixed-grill",
    isAvailable: true,
    name: "Karışık Izgara",
    price: 310.25,
  },
  {
    categoryId: "drinks",
    id: "product-lemonade",
    isAvailable: true,
    name: "Limonata",
    price: 50,
  },
  {
    categoryId: "drinks",
    id: "product-ayran",
    isAvailable: true,
    name: "Ayran",
    price: 40,
  },
  {
    categoryId: "drinks",
    id: "product-tea",
    isAvailable: true,
    name: "Çay",
    price: 50,
  },
  {
    categoryId: "drinks",
    id: "product-sparkling-water",
    isAvailable: true,
    name: "Sparkling Water",
    price: 80,
  },
  {
    categoryId: "dessert",
    id: "product-kunefe",
    isAvailable: true,
    name: "Kunefe",
    price: 220,
  },
  {
    categoryId: "dessert",
    id: "product-salad",
    isAvailable: true,
    name: "Karışık Salata",
    price: 220,
  },
  {
    categoryId: "dessert",
    id: "product-pide",
    isAvailable: true,
    name: "Kaşarlı Pide",
    price: 202.75,
  },
  {
    categoryId: "dessert",
    id: "product-meze",
    isAvailable: true,
    name: "Meze Tabağı",
    price: 310,
  },
  {
    categoryId: "dessert",
    id: "product-manti",
    isAvailable: true,
    name: "Mantı",
    price: 180.125,
  },
  {
    categoryId: "dessert",
    id: "product-soup",
    isAvailable: true,
    name: "Mercimek Çorbası",
    price: 45,
  },
];
